# Generated by Django 2.2.12 on 2023-01-05 15:42

from django.db import migrations, models
import django.db.models.deletion
import factory.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('script', models.TextField()),
                ('part_query', models.CharField(max_length=500)),
                ('execution_style', models.CharField(choices=[('parallel', 'parallel'), ('serial', 'serial')], max_length=10)),
                ('options', factory.fields.MapField(blank=True, default=factory.fields.defaultdict, editable=True, null=True)),
                ('user', models.CharField(max_length=150)),
                ('results', factory.fields.MapField(default=factory.fields.defaultdict, editable=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(choices=[('queued', 'queued'), ('waiting', 'waiting'), ('done', 'done'), ('paused', 'paused'), ('error', 'error'), ('aborted', 'aborted')], max_length=10)),
                ('status', factory.fields.JSONField(blank=True, default=[])),
                ('message', models.CharField(blank=True, default='', max_length=1024)),
                ('script_runner', models.BooleanField(editable=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WorkOrder.WorkOrder')),
            ],
            options={
                'permissions': (('can_base_job', 'Can Work With Base Jobs'), ('can_job_signal', 'Can call the Job Signalling Actions')),
                'default_permissions': (),
            },
        ),
    ]
